broker:
  host: localhost
  port: 4222

db:
  driver: postgres
  host: localhost
  port: 5432
  db_name: user_db
  user: postgres
  password: postgres
  sslmode: disable

redis:
  host: localhost
  port: 6379

